// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
}

// tracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceClone   *ebpf.ProgramSpec `ebpf:"trace_clone"`
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve  *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TracePtrace  *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
	TraceSetuid  *ebpf.ProgramSpec `ebpf:"trace_setuid"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.Events,
	)
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceClone   *ebpf.Program `ebpf:"trace_clone"`
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.Program `ebpf:"trace_openat"`
	TracePtrace  *ebpf.Program `ebpf:"trace_ptrace"`
	TraceSetuid  *ebpf.Program `ebpf:"trace_setuid"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.TraceClone,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceOpenat,
		p.TracePtrace,
		p.TraceSetuid,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfeb.o
var _TracerBytes []byte
